In [2]:
import numpy as np

In [3]:
n = [[1,2,3], [4,5,6], [7,8,9]]
a = np.array(n)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(3, 3)

In [9]:
a[2][2]

np.int64(9)

In [10]:
np.eye((3))                  

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Creating arrays
a = np.array([1, 2, 3])                  # 1D array
b = np.array([[1, 2], [3, 4]])           # 2D array
c = np.zeros((2, 3))                     # Array of zeros
d = np.ones((3, 3))                      # Array of ones
e = np.eye(3)                            # Identity matrix


f = np.arange(0, 10, 2)                  # (start, end, step) # Range of values


g = np.linspace(0, 1, 5)                 # Evenly spaced values

h = np.random.rand(2, 2)                 # Random values

print("1D Array:", a)
print("2D Array:", b)
print("Zeros:", c)
print("Ones:", d)
print("Identity:", e)
print("Arange:", f)
print("Linspace:", g)
print("Random:", h)

1D Array: [1 2 3]
2D Array: [[1 2]
 [3 4]]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random: [[0.4673968  0.37373691]
 [0.88429289 0.88931283]]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", a.shape)             # (2, 3)
print("Size:", a.size)               # 6
print("Data type:", a.dtype)         # int64
print("Number of dimensions:", a.ndim)  # 2

Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2


In [13]:
print(a[0, 1])     # Element at first row, second column
print(a[:, 1])     # All rows, second column
print(a[1, :])     # Second row

2
[2 5]
[4 5 6]


In [14]:
a_reshaped = a.reshape(3, 2)
a_flat = a.flatten()  # 1D array
a_T = a.T
print("Reshaped:", a_reshaped)
print("Flattened:", a_flat)
print("Transposed:", a_T)

Reshaped: [[1 2]
 [3 4]
 [5 6]]
Flattened: [1 2 3 4 5 6]
Transposed: [[1 4]
 [2 5]
 [3 6]]


In [15]:
x = np.array([1, 2, 3, 4])
print("Sum:", np.sum(x))
print("Mean:", np.mean(x))
print("Median:", np.median(x))
print("Std Dev:", np.std(x))
print("Min:", np.min(x))
print("Max:", np.max(x))
print("Argmin:", np.argmin(x))
print("Argmax:", np.argmax(x))

Sum: 10
Mean: 2.5
Median: 2.5
Std Dev: 1.118033988749895
Min: 1
Max: 4
Argmin: 0
Argmax: 3


In [16]:
x

array([1, 2, 3, 4])

In [17]:
y = np.array([10, 20, 30, 40])
y

array([10, 20, 30, 40])

In [18]:
x * y

array([ 10,  40,  90, 160])

In [19]:

print("Addition:", x + y)
print("Subtraction:", y - x)
print("Multiplication:", x * y)
print("Division:", y / x)
print("Square root:", np.sqrt(x))
print("Exponential:", np.exp(x))
print("Logarithm:", np.log(x))

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Square root: [1.         1.41421356 1.73205081 2.        ]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Logarithm: [0.         0.69314718 1.09861229 1.38629436]


In [20]:
print(x)
x[x > 3]

[1 2 3 4]


array([4])

In [21]:
mask = x > 2
print("Mask:", mask)
print("Filtered:", x[mask])

Mask: [False False  True  True]
Filtered: [3 4]


In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Dot Product:", np.dot(a, b))
print("Matrix Mult:", a @ b)

Dot Product: [[19 22]
 [43 50]]
Matrix Mult: [[19 22]
 [43 50]]


In [23]:
print("Determinant:", np.linalg.det(a))
print("Inverse:", np.linalg.inv(a))
print("Eigenvalues:", np.linalg.eig(a))

Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [24]:
np.random.seed(0)
print("Random integers:", np.random.randint(0, 10, (2, 3)))
print("Random floats:", np.random.rand(2, 2))
print("Normal dist:", np.random.randn(2, 2))

Random integers: [[5 0 3]
 [3 7 9]]
Random floats: [[0.6235637  0.38438171]
 [0.29753461 0.05671298]]
Normal dist: [[-0.1730696  -1.76165167]
 [-0.08767307  1.36687937]]
